# Generated by Django 4.2.7 on 2023-11-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('modification_name', models.CharField(max_length=100)),
                ('modification_id', models.IntegerField()),
                ('configuration_id', models.IntegerField()),
                ('tech_param_id', models.IntegerField()),
                ('body_type', models.CharField(max_length=100)),
                ('years', models.CharField(max_length=100)),
                ('complectations', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoru_service.mark')),
            ],
        ),
    ]
